server:
  port: 8082
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.222.170.65:8761/eureka 

spring:
  application:
    name: user-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://35.222.170.65:3306/app_dev
    username: myuser
    password: "@Autowired123"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true